// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    
    // Original protobuf compilation for gRPC
    tonic_build::configure()
        .build_server(true)
        .protoc_arg("--experimental_allow_proto3_optional")
        .compile(
            &["proto/auth.proto"],
            &["proto", "proto/google/protobuf", "proto/prost"],
        )
        .unwrap_or_else(|e| panic!("protobuf compilation failed: {}", e));
}
